post_install() {
	mv -f etc/os-release_crystal etc/os-release
	mv -f usr/lib/os-release_crystal usr/lib/os-release
	mv -f etc/issue_crystal etc/issue
	mv -f etc/lsb-release_crystal etc/lsb-release
	        
	if [ -f /etc/default/grub ]; then
		sed -i s/GRUB_DISTRIBUTOR=\"Arch\"/GRUB_DISTRIBUTOR=\"Crystal\"/g etc/default/grub
		grub-mkconfig -o /boot/grub/grub.cfg
	fi
}

post_upgrade() {
	post_install
}
