post_install() {
	mv -f etc/os-release_crystal etc/os-release
	mv -f etc/issue_crystal etc/issue
        sed -i s/GRUB_DISTRIBUTOR=\"Arch\"/GRUB_DISTRIBUTOR=\"Crystal\"/g etc/default/grub
        grub-mkconfig -o /boot/grub/grub.cfg
}

post_upgrade() {
	mv -f etc/os-release_crystal etc/os-release
        mv -f etc/issue_crystal etc/issue
        sed -i s/GRUB_DISTRIBUTOR=\"Arch\"/GRUB_DISTRIBUTOR=\"Crystal\"/g etc/default/grub
        grub-mkconfig -o /boot/grub/grub.cfg
}
